apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  - image: quay.io/scottcranton/grpc-route-guide-server
    docker:
      dockerfile: Dockerfile
  local: {}
deploy:
  kubectl:
    manifests:
    - deployment.yaml
